version: '3.9'
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    env_file:
      - ./.env
    networks:
      - backend

  express-app:
    container_name: express-app
    build: .
    command: yarn start
    ports:
      - '6476:6476'
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    depends_on:
      - mysql-db
    env_file:
      - ./.env
    networks:
      - backend
networks:
  backend:
    driver: bridge

